### ISSUE TITLE
Hidden tracking via Google Analytics?

### ISSUE THREAD

**Issue by ModischFabrications** [ryangrose/easy-pandoc-templates#3]
Looking through the HTML code it seems like Google Analytics is implicitly included. This seems to be neither part of the readme nor of user settings. Are you offering it as an extension to the user or tracking installs of your template?

Hidden tracking is a big "no-no" for GDPR, am I missing something? 

easy_template.html:
```
$if(analytics)$                    
            <script>
                  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '$analytics$', 'auto');
  ga('send', 'pageview');
$endif$
```

**Comment by ryangrose** [comment]
Hey @ModischFabrications, thanks for catching this.

I didn't intend any tracking. I sourced these templates from other repos and modified them to work from anywhere. Because it's wrapped in the "if analytics" clause it won't be included unless that flag is passed. Just confirmed it myself.

In any case, I've removed that block from the templates: [fix: remove google analytics](https://github.com/ryangrose/easy-pandoc-templates/commit/0d98f82c1f0b9e8a5d99f28cc49f9def162894d6)
